theme: jekyll-theme-cayman
title: Implementação da plataforma GamingAnywhere para análise de mídia
description: >
  Este é um projeto desenvolvido na disciplina de Sistemas Multimídia
  do Curso de Engenharia de Telecomunicações do IFSC câmpus São José -
  primeiro semestre de 2019.
baseurl: '/SMU29009'
url: 'https://yanmartins.github.io/SMU29009'
github_username: yanmartins
